name: My First Workflow

on: push

jobs:
    fist_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Welcome message
              run: echo "My first Github Action Job"

            - name: List Files
              run: ls

            - name: Read Files
              run: cat README.md
