name: Generate ASCII Artwork

on:
    push

jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a dragon....RAWR" >> dragon.txt

        - name: Upload the Dragon text file
          uses: actions/upload-artifact@v4
          with:
                name: dragon-test-file
                path: dragon.txt

    test_job2:
        needs: build_job1
        runs-on: ubuntu-latest
        steps:
        - name: Download the Dragon text file
          uses: actions/download-artifact@v4
          with:
                name: dragon-test-file

        - name: Test File Exits
          run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: test_job2
        runs-on: ubuntu-latest
        steps:
        - name: Download the Dragon text file
          uses: actions/download-artifact@v4
          with:
                name: dragon-test-file
                
        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying... ... .