name: Artifact

on: [push]   #brackets if needs to add additional request like pull 

env:
  ARTIFACT_NAME: myartifact
  
jobs:
  main:                         #since it has one job we are using main keyword
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
      
